Add some comment code
MakeShiftArtist/iFunny.ts pull request #2
Opened 2023-11-19 18:16 UTC by gastrodon

Get our own comments iterator 
Delete comments we have a handle on 

### still TODO 
- need to handle the [orphan comment](https://github.com/MakeShiftArtist/iFunny.ts/blob/2f896fdc7e63d702a41548ab55c9d754163d8fab/src/client/Client.ts#L333) error for real
- would be nice to not need to fetch content for each comment

2025-04-05 23:32 UTC, MakeShiftArtist requested changes
The current design has only getters / attributes in the Base classes. Methods like `delete()`, `smile()`, etc should be the in the `Comment` class.

For consistency, this needs to be moved to the `Comment` class. And avoid using `<any>` unless absolutely required. If required, add a comment on why.

2025-04-12 02:40 UTC, gastrodon commented
I will have to get a dev setup for ifunny again but I will take a look at these requested changes

2025-05-06 18:43 UTC, gastrodon commented
Hey so about orphan comments - how do we want to handle that? It seems like the issue has nothing to do with the comment itself but rather getting a content object to attach to it - I wonder if we need to be doing that? 

A few thoughts 
- probably don't want to skip them or especially throw because the comment _is_ there
- without really being up to date on the library, I think we need a content because the comment route is `.../{cid}/comments/{commend_id}`. If a content is missing are the links to its individual comments still valid? 
- whether or not the url it is still valid, we should just be able to construct the comment normally without initiating a fetch of the client. If it's not valid, we have a comment that can't be updated... which seems fine?

2025-10-09 02:38 UTC, MakeShiftArtist commented
> It seems like the issue has nothing to do with the comment itself but rather getting a content object to attach to it - I wonder if we need to be doing that?

Technically we don't and I would actually prefer NOT to automatically fetch the content every time. I think explicitly calling `await Comment.content()` would be the preferred solution, however this has not yet been implemented.

If you'd like to properly handle this, you can, otherwise I'm okay with merging what we have and focus on a mild rewrite avoiding inheritance all together, and making sure we ONLY make network requests explicitly. In this rewrite we can properly handle the content not existing by just not fetching it automatically.

This would require intermediate classes that only contain partial data. From those, we should be able to fetch the full data using the `.fetch()` method.

Something like so

```ts
/**
 * Represents a Comment on iFunny
 * @extends BaseComment
 */
export class Comment extends BaseComment {
	/**
	 * @param client The client instance
	 * @param payload Payload of the Comment
	 */
	public constructor(client: Client, payload: APIComment) {
		super(client, payload);
	}
}
```

And then modify the BaseComment like so
```ts
	/**
	 * @param client The client instance
	 * @param payload Payload of the Comment
	 */
	public constructor(client: Client, payload: APIComment) {
		super(client, payload);
		// this.#content = content;
		// this.payload.cid should ALWAYS exist
		this.endpointUrl = Endpoints.comments(this.payload.cid, this.payload.id);
	}
```

This is actually more consistent with other Base classes, however it would require changing `Comment.content` to an async function rather than a getter function.

2025-10-09 02:42 UTC, MakeShiftArtist approved these changes
Current design would need some changes to properly handle orphan comments, however I don't actually think orphan comments would cause an issue for most usage. Either way really it's going to require breaking changes.

If you want to merge what you have, we can refactor to properly handle orphan comments later.

2025-12-15 04:13 UTC, MakeShiftArtist commented
The project is undergoing a small rewrite to improve developer workflow using nix and bun, so this now has conflicts. I'm eventually going to get rid of the whole "Base[Struct]" paradigm and reduce inheritance and "clever" typing to make the overall codebase more readable and maintainable. No ETA when this is planned so if this PR is updated to fit with the new changes, I'll be happy to merge it.

2026-04-08 07:53 UTC, closed without merging